#!/bin/sh
set -e

DEFAULT_DISPLAY_MANAGER_FILE=/etc/X11/default-display-manager
DEFAULT_SERVICE=/etc/systemd/system/display-manager.service

case "$1" in
    purge)
        update-rc.d sddm remove > /dev/null

        if [ -d /var/cache/sddm ]; then rm -r /var/cache/sddm; fi
        if [ -d /var/lib/sddm ]; then rm -r /var/lib/sddm; fi
        if [ -d /var/run/sddm ]; then rm -r /var/run/sddm; fi
        if [ -d /var/log/sddm ]; then rm -r /var/log/sddm; fi
        if [ -d /run/sddm ]; then rm -r /run/sddm; fi
        if [ -f /var/log/sddm.log ]; then rm /var/log/sddm.log; fi

        if getent passwd sddm >/dev/null; then
            if [ -x /usr/sbin/deluser ]; then
                deluser --system sddm >&2 ||
                    echo "Could not remove sddm user." >&2
            fi
        fi
        if getent group sddm >/dev/null; then
            if [ -x /usr/sbin/delgroup ]; then
                delgroup --system sddm >&2 ||
                    echo "Could not remove sddm group." >&2
            fi
        fi
        if [ ! -e "$DEFAULT_DISPLAY_MANAGER_FILE" ] &&
            [ -h "$DEFAULT_SERVICE" ] && [ ! -e "$DEFAULT_SERVICE" ]; then
            # Dangling symlink, no other display-manager installed
            rm "$DEFAULT_SERVICE"
        fi

        ;;
    abort-install|abort-upgrade)
        # roll back displacement of default display manager file
        if [ -e "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp" ]; then
            # FIXME - redo this part uses shell-lib.sh from xfree86
            #observe "rolling back change of default X display manager"
            mv "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp" "$DEFAULT_DISPLAY_MANAGER_FILE"
        fi
        ;;
esac
# Automatically added by dh_installdeb/13.24.2ubuntu1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/sddm_org.freedesktop.DisplayManager.conf 0.21.0-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'sddm.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/13.24.2ubuntu1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

exit 0
